### ISSUE TITLE
hit highlighting not working

### ISSUE THREAD

**Issue by srabun** [uoregon-libraries/oregonnews#34] opened 2015-04-02 16:52 UTC
User reported that the red search terms highlighting on search results is not working on Oregon City newspapers. I tested this on Oregon City newspapers but also on others and found this to be true - for some reason the search results are not highlighted on the thumbnails as they should be.

I tested in chrome - I got like one or two highlights for a few pages, but overall the hit highlighting is not working...please help

@jechols @lsat12357

**Comment by srabun** [comment] 2015-04-02 18:05
I think it might have to do with the fact that we just re-loaded the Oregon City batches with the new batch names. All I did was change the batch names, so that should not have made a difference to the files..I'm confused

**Comment by lsat12357** [comment] 2015-04-02 19:45
so there is at least one batch right in the middle of all of these that is fine, batch_confederatedtribesofwarmsprings_ash_ver01
it looks like when the search results load, this error happens
http://oregonnews.uoregon.edu/lccn/sn96088160/1894-12-27/ed-1/seq-4/coordinates/ Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by jechols** [comment] 2015-04-03 16:40
Can I get a URL that this happens on?  Just do a search and copy/paste the URL.

@lsat12357, the URL you posted above gives me a word coordinates file, so I'm not sure what I should be looking for.

**Comment by jechols** [comment] 2015-04-03 23:48
Given that a purge/reload was started yesterday, there's no way to know if this is fixed or not until probably Monday.

@srabun, I'd still like a URL for reproducing this so that on Monday I can look to see if the reload is going to fix things or not.  I'm not sure if you still have one, but maybe at least describe how you go to the broken search results.  Did you just click "Oregon City" from the home page and do a random search?

**Comment by srabun** [comment] 2015-04-04 05:23
@jechols All of the content/batches that were not working before are now working so i don't have a url for the problem. (I failed to provide even a screenshot, sorry! ) Basically, I just went to the search page (http://oregonnews.uoregon.edu/search/pages/) and in the "Select Newspaper(s)" box I selected several Oregon City newspapers and searched for "Oregon" for example, and the results came up, but the word Oregon was not highlighted on pages that were part of the recent ingest of special batch names. I tested and all of the content in the special batches that were recently ingested, with the exception of the confederatedtribesofwarmsprings_ash batch, were not turning up highlighted results. All of the regular-named, previously loaded batches, as well as both confederatedtribesofgrandronde batches (flora and horseheaven), were working fine.

So, now when I do a search within Oregon City newspapers, I get these results with the highlighting working: http://oregonnews.uoregon.edu/search/pages/results/?date1=1846&date2=2013&searchType=advanced&lccn=sn83025129&lccn=sn00063694&lccn=sn00063696&lccn=sn00063698&lccn=sn00063697&lccn=sn00063700&lccn=sn94052321&lccn=sn84022660&proxdistance=5&rows=20&ortext=oregon&proxtext=&phrasetext=&andtext=&dateFilterType=yearRange&page=1&sort=relevance 

Let me know if you need more info. But is seems to be working now. Just weird that almost all of the newly loaded special-named batches weren't turning up highlighted results...and after re-loading they are working now.

**Comment by jechols** [comment] 2015-04-06 16:15
Very odd, indeed.  I'm closing this for now, as there's nothing more to do at the moment.  If we see it again, I think the solution is just to reload the affected batches, but I'd like to spend some time looking at the site and possibly the batch load logs or something.  I'm hoping this was a fluke, but if it turns out to be a more widespread problem, we'll need to try and figure out the cause so we can prevent it in the future.

**Closed by jechols** 2015-04-06 16:15 UTC
